### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by AmmarOnah** [ahmedshamsddin/github-docs#12]
@ahmedshamsddin I like the edits made on the background and the text alignments, search bar they are clean.
I do Believe that text must be in white because having black text on a dark background is hard for reading, also it's better for text to be a bit bigger to enhance the ability of reading it, and bolder when it comes to big titles of an article or something.

I Believe these things will enhance the template in being a better looking, more modern design  &  easier to read.
What do you think Ahmad & Everyone?

**Comment by ahmedshamsddin** [comment]
Actually the background color of the template is white so text of content should stay black. You can increase the size of the content a bit and make headers bold thats a good suggestion

**Comment by AmmarOnah** [comment]
@ahmedshamsddin brooo my bad you did exactly what I was trying to say, but im not loading the page correctly so i see a totally different thing than the final product, now after seeing it I say Wow you did now even better than what in my mind its simple clean easier to read.

Even your choice of text it's now fitting to the overall design.

I guess a good thing we learn than we should not judge a design until its fully completed, also its great to have votes for which template is better because a beautiful template should be beautiful in the eyes of most people
