### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by ahmedshamsddin** [ahmedshamsddin/github-docs#15]
@AmmarOnah I added the template to the index html please try adding the content today if you can. If not we can assign it to someone else

@aziza251 Please try fixing the issues in the commands.html by resolving the merge conflict and using latest version of the template.html file

@Mimi2694 @Muntaha1314 Please start with the faqs.html the file is still empty

@lulwaajlani @rihambkr Please add the template to your practices.html file then add the html content before merging your branch

@MohamedEldushi Please do the README.md file

**Comment by aziza251** [comment]
@ahmedshamsddin i am done with my page. Can you please check and approve or if there is anything should be done, inform me. Thank you

**Comment by aziza251** [comment]
> @ahmedshamsddin i am done with my page. Can you please check and approve or if there is anything should be done, inform me. Thank you

**Comment by AmmarOnah** [comment]
Im doing it now as alhamdullelah i got cured, will be pushing it before İsha prayer inshaa allah
