### ISSUE TITLE
template

### ISSUE THREAD

**Issue by aziza251** [ahmedshamsddin/github-docs#16]
i think something is wrong with the template. before it was changed it worked good on my content page but now after i copied and pasted the new template, there is soemthing huge on the screen and i cand remove it.can you please check it?

**Comment by ahmedshamsddin** [comment]
@aziza251 Okay I will check it now and try to fix it. Thank you!

**Comment by ahmedshamsddin** [comment]
@aziza251 Can you check the page now I fixed the issue
https://ahmedshamsddin.github.io/github-docs/commands.html

**Comment by aziza251** [comment]
@ahmedshamsddin yes its okay now thank you.
