### ISSUE TITLE
Tempate and design 

### ISSUE THREAD

**Issue by ahmedshamsddin** [ahmedshamsddin/github-docs#3]
@MaesAlzaeim Please try finishing the template by tomorrow max. Make your changes and commit on the template.html file in the main branch

@AmmarOnah upload to our repo the colors and fonts needed four the design also by tomorrow max.

Thanks in advance, good luck!!

**Comment by ahmedshamsddin** [comment]
Yes Ammar you primary work will be in index.html file. You can put the colors and fonts in a text file and push it to this repo

**Comment by AmmarOnah** [comment]
@ahmedshamsddin 
@MaesAlzaeim 
Colors&Fonts txt File Has been Added.
Tell me What You think, I Tried To make it Super simple only 2 colors with not transparency and stuff.

**Comment by MaesAlzaeim** [comment]
@ahmedshamsddin 
@AmmarOnah 
should i add the fonts and colors to the template?  And can i share what ive done so far so i can confirm if i am on the right path or not, before learning how to add the fonts and colors if i had to?

**Comment by AmmarOnah** [comment]
I guess you should be using the fonts&colors to make a page that is a reference for all so they copy it design. I have a pre-made design with these fonts & colors I actually designed on Wix.com until kinda got satisfied.

I'll send you a picture and I guess you will have to try making it in HTML CSS if im not mistaking, for the help if you are on right Way I don't think it's a bad idea , send and we will help you inshaa allah and the earlier you send the better 🫡🫡 we are here together don't worry I started from 0 today and kinda killing it now

**Comment by ahmedshamsddin** [comment]
@MaesAlzaeim Yes for sure you can push your current work and we will check it out . Actually these colors and fonts will be used in the css file and linked to the html to apply the styles

**Comment by MaesAlzaeim** [comment]
@ahmedshamsddin @AmmarOnah i just did, yet i pushed it by dragging the file (which is probably wrong) cuz using the terminal did not work for me idk why but if its wrong i can delete it and find another way to push it again , please check the template and tell me if its correct or not

**Comment by AmmarOnah** [comment]
@MaesAlzaeim Check the wiki, there is a 6m youtube video I posted there that teaches from zero to before the merging conflicts topic, try doing what he did because he was the one who saved me

**Comment by ahmedshamsddin** [comment]
@MaesAlzaeim thank you Maes your work is amazing I just saw it. We will fix some issues in the file today and work it together so we can start with other content so make sure to attend the session. @AmmarOnah thank you for the fonts and colors too.

**Comment by AmmarOnah** [comment]
🫡🫡, I couldn't get zoom link because I was providing them with the Administration Receipt, I'm waiting for their reply they should provide me with the link to join
