### ISSUE TITLE
Start preparing content

### ISSUE THREAD

**Issue by ahmedshamsddin** [ahmedshamsddin/github-docs#4]
Hey guys, you can start preparing the content of your pages from now while Maes and Ammar are preparing the designs and template we need

Good luck!

**Comment by MohamedEldushi** [comment]
This is the link of UX interface for **home page.**

[](https://www.figma.com/proto/rTxUi8aAFUWhVXwn4hVSFx/Untitled?type=design&node-id=1-2&t=gPytztT2Elj4z3nE-1&scaling=scale-down&page-id=0%3A1&mode=design)
